### ISSUE TITLE
Missing licensing information

### ISSUE THREAD

**Issue by peterjc** [DRL/kinfin#1]
See e.g. https://help.github.com/articles/open-source-licensing/

Traditionally (unless opting for the GNU GPL) use a file named ``LICENSE``, ``LICENSE.txt`` or ``LICENSE.md`` etc if using a markup language, and put put the name of the license in the Python file header and the main README file.

I would suggest picking an open source licence from https://opensource.org/

**Comment by DRL** [comment]
Thank you, Peter!

added a GNU GPL3 license
