### ISSUE TITLE
structure of SpeciesClassification.txt

### ISSUE THREAD

**Issue by evolgenomology** [DRL/kinfin#12]
Hey Dom,

would you mind shortly explaining to me the structure of the *SpeciesClassification.txt* file. 
What is the OUT field for, what can I get by using the labels, e.g. should these be taxa?
Also which names do I need to put in the PROTEOME section?

Thanks

Phil

**Comment by DRL** [comment]
Hi Phil!

Re structure:
- CSV
- Some fields (IDX, PROTEOME, OUT, taxid) are "special" columns, which mean that their content changes the analysis
- IDX: Following OrthoFinder-convention this is the index given to the proteome. ProteinIDs in orthogroups get mapped through the ```SequenceIDs.txt``` file to their proteomes based on that index.  
- PROTEOME: The name given to this proteome in the scope of the analysis. The shorter the better (I tend to use a 5 letter prefix, which I also put in front of sequenceIDs in FASTA files)
- OUT: This determines the outgroup(s). Binary. ```0```="not outgroup", ```1```="outgroup". If a newick tree is provided, KinFin will try to root that tree using the outgroup (or LCA of outgroups). All this requires the ETE3 python API to be (properly) installed.
- taxid : if present, KinFin will automatically assign proteomes to groups at certain taxonomic ranks (specified through the ```--taxranks```option) based on their taxids (and the ```nodesDB``` file, which is in the ```data/``` folder). Only do the taxonomic ranks you are interested in.  
- You can add as many more columns as you want, the column title is then the ```attribute``` (e.g: "parasitism") and the values for each proteome are the ```levels``` (e.g. "free-living", "animal-parasitic", ...). 
- During the analysis, ```levels``` of an ```attribute``` are compared against each other.

In general:
- It makes sense to build groups (either through labelling or sample selection in the clustering) so that they include ≥2 proteomes. 
- It also helps if groups of interest are composed of equal number of proteomes.  
- Take a look at the test-files in the ```test_data/``` folder. They are simple files and will give you a feel of how things work.

Hope this is helpful. Let me know if more issues arise. 

Haven't had time yet to document this.

All the best, 

dom

**Comment by evolgenomology** [comment]
Hi Dom, Thanks a lot. Actually, had guessed the IDX field. :-) One question towards the PROTEOME field, does it check only for a string match of the species code, i.e. can I use e.g. my PSU.faa file name, or does it have to be called PSU.proteome.fasta?CiaoPhil Sent with SolMail App--------- Original Message ---------
From: Dominik R Laetsch 
To: DRL/kinfin 
Date: Wed Dec 21 21:23:47 GMT+00:00 2016
Subject: Re: [DRL/kinfin] structure of SpeciesClassification.txt (#12)

Hi Phil!
Re structure:

CSV
Some fields (IDX, PROTEOME, OUT, taxid) are "special" columns, which mean that their content changes the analysis
IDX: Following OrthoFinder-convention this is the index given to the proteome. ProteinIDs in orthogroups get mapped through the SequenceIDs.txt file to their proteomes based on that index.
PROTEOME: The name given to this proteome in the scope of the analysis. The shorter the better (I tend to use a 5 letter prefix, which I also put in front of sequenceIDs in FASTA files)
OUT: This determines the outgroup(s). Binary. 0="not outgroup", 1="outgroup". If a newick tree is provided, KinFin will try to root that tree using the outgroup (or LCA of outgroups). All this requires the ETE3 python API to be (properly) installed.
taxid : if present, KinFin will automatically assign proteomes to groups at certain taxonomic ranks (specified through the --taxranksoption) based on their taxids (and the nodesDB file, which is in the data/ folder). Only do the taxonomic ranks you are interested in.
You can add as many more columns as you want, the column title is then the attribute (e.g: "parasitism") and the values for each proteome are the levels (e.g. "free-living", "animal-parasitic", ...).
During the analysis, levels of an attribute are compared against each other.

In general:

It makes sense to build groups (either through labelling or sample selection in the clustering) so that they include ≥2 proteomes.
It also helps if groups of interest are composed of equal number of proteomes.
Take a look at the test-files in the test_data/ folder. They are simple files and will give you a feel of how things work.

Hope this is helpful. Let me know if more issues arise.
Haven't had time yet to document this.
All the best,
dom

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DRL/kinfin","title":"DRL/kinfin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DRL/kinfin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DRL in #12: Hi Phil!\r\n\r\nRe structure:\r\n- CSV\r\n- Some fields (IDX, PROTEOME, OUT, taxid) are \"special\" columns, which mean that their content changes the analysis\r\n- IDX: Following OrthoFinder-convention this is the index given to the proteome. ProteinIDs in orthogroups get mapped through the ```SequenceIDs.txt``` file to their proteomes based on that index.  \r\n- PROTEOME: The name given to this proteome in the scope of the analysis. The shorter the better (I tend to use a 5 letter prefix, which I also put in front of sequenceIDs in FASTA files)\r\n- OUT: This determines the outgroup(s). Binary. ```0```=\"not outgroup\", ```1```=\"outgroup\". If a newick tree is provided, KinFin will try to root that tree using the outgroup (or LCA of outgroups). All this requires the ETE3 python API to be (properly) installed.\r\n- taxid : if present, KinFin will automatically assign proteomes to groups at certain taxonomic ranks (specified through the ```--taxranks```option) based on their taxids (and the ```nodesDB``` file, which is in the ```data/``` folder). Only do the taxonomic ranks you are interested in.  \r\n- You can add as many more columns as you want, the column title is then the ```attribute``` (e.g: \"parasitism\") and the values for each proteome are the ```levels``` (e.g. \"free-living\", \"animal-parasitic\", ...). \r\n- During the analysis, ```levels``` of an ```attribute``` are compared against each other.\r\n\r\nIn general:\r\n- It makes sense to build groups (either through labelling or sample selection in the clustering) so that they include ≥2 proteomes. \r\n- It also helps if groups of interest are composed of equal number of proteomes.  \r\n- Take a look at the test-files in the ```test_data/``` folder. They are simple files and will give you a feel of how things work.\r\n\r\nHope this is helpful. Let me know if more issues arise. \r\n\r\nHaven't had time yet to document this.\r\n\r\nAll the best, \r\n\r\ndom"}],"action":{"name":"View Issue","url":"https://github.com/DRL/kinfin/issues/12#issuecomment-268643761"}}}

**Comment by DRL** [comment]
Github lost against your mail client, it seems ... :)

PROTEOME is not used for matching, but for making output more readable.

Matching is done through:
- ```SequenceIDs.txt``` : proteinID -> proteomeIDX
- ```SpeciesClassification.txt``` : proteomeIDX -> proteomeID (+other attributes)
- ```SpeciesIDs.txt``` : FASTA file -> proteomeIDX (this is optional, only affects length stats)

cheers, 

dom

**Comment by evolgenomology** [comment]
Thanks! Will run it first thing tomorrow morning. PhilSent with SolMail App--------- Original Message ---------
From: Dominik R Laetsch 
To: DRL/kinfin 
Date: Wed Dec 21 21:43:33 GMT+00:00 2016
Subject: Re: [DRL/kinfin] structure of SpeciesClassification.txt (#12)

Github lost against your mail client, it seems ... :)
PROTEOME is not used for matching, but for making output more readable.
Matching is done through:

SequenceIDs.txt : proteinID -> proteomeIDX
SpeciesClassification.txt : proteomeIDX -> proteomeID (+other attributes)
SpeciesIDs.txt : FASTA file -> proteomeIDX (this is optional, only affects length stats)

cheers,
dom

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DRL/kinfin","title":"DRL/kinfin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DRL/kinfin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DRL in #12: Github lost against your mail client, it seems ... :)\r\n\r\nPROTEOME is not used for matching, but for making output more readable.\r\n\r\nMatching is done through:\r\n- ```SequenceIDs.txt``` : proteinID -\u003e proteomeIDX\r\n- ```SpeciesClassification.txt``` : proteomeIDX -\u003e proteomeID (+other attributes)\r\n- ```SpeciesIDs.txt``` : FASTA file -\u003e proteomeIDX (this is optional, only affects length stats)\r\n\r\ncheers, \r\n\r\ndom\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/DRL/kinfin/issues/12#issuecomment-268648603"}}}
