### ISSUE TITLE
filter_fastas_before_clustering.py

### ISSUE THREAD

**Issue by clydeandforth** [DRL/kinfin#22]
Hi Dom,

I get the following error when sanitising .faa files:

./scripts/filter_fastas_before_clustering.py -f example/fasta/
Traceback (most recent call last):
  File "./scripts/filter_fastas_before_clustering.py", line 93, in <module>
    main(args)
  File "./scripts/filter_fastas_before_clustering.py", line 56, in main
    min_stops = int(args['--stops'])
KeyError: '--stops'

In the readme.io I don't understand this - 'not exceeding the number of stops (*) (--stops INT, default 0).'

Thanks,

James

**Comment by DRL** [comment]
Hi James, 

Well spotted, the command line argument was not passed on to the script. I fixed it now and and if you download the new release (or git pull) it should work.

Regarding the argument '--stops INT', it determines how many non-terminal stops (i.e. "*") are allowed in a sequence to pass the filter. Normally one would not want non-terminal stops in proteins as these are an indication of a misprediction.

One other thing, the input for filter_fastas_before_clustering should be a FASTA file, not the directory containing the FASTA files.

Please let me know if this helps.

cheers, 

dom

**Comment by clydeandforth** [comment]
Hi Dom,

That got it.

Thanks,

James
