### ISSUE TITLE
generate_network.py

### ISSUE THREAD

**Issue by clydeandforth** [DRL/kinfin#23]
Hi Dom,

When running the generate_network.py script from my kinfin output I get the following error;

./scripts/generate_network.py -m JD_kinfin_results.kinfin_results/all/all.cluster_summary.txt -c config.txt
[+] Parsing SpeciesClassification file: config.txt ...
[+] Parsing JD_kinfin_results.kinfin_results/all/all.cluster_summary.txt ...
[-] No column header ending in '_count' found in #cluster_id,cluster_protein_count,protein_median_count,TAXON_count,attribute,attribute_cluster_type,protein_span_mean,protein_span_sd,all_count,all_median,all_cov

The clustering file starts like this:

#cluster_id     cluster_protein_count   protein_median_count    TAXON_count     attribute       attribute_cluster_type  protein_span_mean       protein_span_sd all_count       all_median      all_cov
OG0000000       1387    698.0   1       all     specific        N/A     N/A     698     0.0     0.05
OG0000001       769     385.0   1       all     specific        N/A     N/A     385     0.0     0.05
OG0000002       590     295.0   1       all     specific        N/A     N/A     295     0.0     0.05

Cheers,

James

**Comment by DRL** [comment]
Hi James, 

sorry, that is a bug. It is meant to be run on ```*.cluster_summary.txt``` (e.g. ```TAXON.cluster_summary.txt```, which is what you want). 

```
~/git/kinfin/scripts/generate_network.py  -m ~/git/kinfin_manuscript/supplementary_material/supplementary_data_3/kinfin.advanced.kinfin_results/TAXON/TAXON.cluster_summary.txt -c ~/git/kinfin_manuscript/supplementary_material/supplementary_data_2/kinfin.config.advanced.txt
[+] Parsing SpeciesClassification file: /Users/dom/git/kinfin_manuscript/supplementary_material/supplementary_data_2/kinfin.config.advanced.txt ...
[+] Parsing /Users/dom/git/kinfin_manuscript/supplementary_material/supplementary_data_3/kinfin.advanced.kinfin_results/TAXON/TAXON.cluster_summary.txt ...
[+] Max edge weight is 11579, ...
[+] Building graphs
Name: Graph
Type: Graph
Number of nodes: 19
Number of edges: 171
Average degree:  18.0000
[+] Saving network graph.graphml
[+] Saving network graph.gexf
```

```all.cluster_summary.txt``` is actually wrongly named. Well spotted. Will change.

cheers, 

dom

**Comment by DRL** [comment]
Pushed to master

**Comment by Yixiangzhang1996** [comment]
Hi Dom,

When running the generate_network.py script from my kinfin output I get the following error;

`(python27) [zyx@node01 TAXON]$ python ~/my_kinfin/kinfin-1.0.3/scripts/generate_network.py -m TAXON.cluster_summary.txt -c config.txt
[+] Parsing SpeciesClassification file: config.txt ...
[+] Parsing TAXON.cluster_summary.txt ... 
[+] Max edge weight is 9918, ...
[+] Building graphs
Traceback (most recent call last):
  File "/home1/zyx/my_kinfin/kinfin-1.0.3/scripts/generate_network.py", line 190, in <module>
    construct_graphs(weighted_edges, proteomeObj_by_proteome_id, attributes)
  File "/home1/zyx/my_kinfin/kinfin-1.0.3/scripts/generate_network.py", line 111, in construct_graphs
    G.add_node(proteomeObj.proteome_id, {k :v for k, v in proteomeObj.level_by_attribute.items()})
TypeError: add_node() takes exactly 2 arguments (3 given)
`
