### ISSUE TITLE
Can't produce the SequenceIDs file

### ISSUE THREAD

**Issue by dcopetti** [DRL/kinfin#24]
Hello,
I am having issues generating the input files using generate_kinfin_files_from_fastas.py (different name from [here](https://kinfin.readme.io/docs/generate_kinfin_files_from_fastaspy), but I assume it is the same). 
The command is 
`generate_kinfin_files_from_fastas.py -f /../../fastas/ -o test orthofinder`
and the error is:

```
[+]      28292 sequences parsed
[+] Parsing file /../../fastas/Ahip50.faa ...
Traceback (most recent call last):
  File "../kinfin/scripts/generate_kinfin_files_from_fastas.py", line 104, in <module>
    dataCollection = DataCollection(fasta_dir, outprefix, orthofinder_flag, config_flag)
  File "../kinfin/scripts/generate_kinfin_files_from_fastas.py", line 58, in __init__
    self.parse_fasta_dir()
  File "../kinfin/scripts/generate_kinfin_files_from_fastas.py", line 72, in parse_fasta_dir
    self.parse_fasta_f(fasta_f, species_idx)
  File "../kinfin/scripts/generate_kinfin_files_from_fastas.py", line 80, in parse_fasta_f
    if line[0] == '>':
IndexError: string index out of range
```
I could run this Ahip file in Orthofinder without problems,do you have a more detailed explanation of what is causing the error?
Thanks,
Dario

**Comment by DRL** [comment]
Hi Dario, 

could it be that ```/../../fastas/Ahip50.faa``` has empty lines?

can you run ```grep -c '^$' /../../fastas/Ahip50.faa``` ?

cheers, 

dom

**Comment by dcopetti** [comment]
yep, it was the empty spaces.
I re run the script and it works now.
Thanks!

**Comment by DRL** [comment]
Hi Damien, 

glad it worked. Nevertheless I pushed a commit to ```generate_kinfin_input.py``` that makes it ignore empty lines now.

cheers, 

dom
