### ISSUE TITLE
enrichment/depletion of one TAXON against all other TAXON

### ISSUE THREAD

**Issue by wdermauw** [DRL/kinfin#25]
Hi 

I investigated the Kinfin results from the example of the KinFin manuscript (kinfin.advanced.kinfin_results/TAXON/) and noticed that none of the nematode species had sign. enriched orthogroups compared to other species while when groups (host, genus) are compared (e.g. kinfin.advanced.kinfin_results/hosts/ or kinfin.advanced.kinfin_results/hosts/) there are sign. enriched orthogroups.

So thus I'm wondering whether is is possible to find sign. enriched orthogroups when comparing single species?

In my setup I have five species from one phylum (A), and one species outgroup from another phylum (C. elegans) (six species in total) and I would like to know whether in one of these five A species there is an enrichment/depletion of orthogroups.

Thank you in advance!

Regards

Wannes

**Comment by DRL** [comment]
Hi Wannes, 

>In my setup I have five species from one phylum (A), and one species outgroup from another phylum (C. elegans) (six species in total) and I would like to know whether in one of these five A species there is an enrichment/depletion of orthogroups.

Regarding your data, just create a new column in the config file where you give label one group as "A" and the other group as "B" (or something else, kinfin does not care about the names of groups... just creates sets based on the strings). When running it, it will do enrichment/comparisons between all sets as long as the sets have equal or more members than ```--min_proteomes``` (which defaults to 2).  

Let me know if this helps.

cheers, 

dom
