### ISSUE TITLE
functional_annotation_of_clusters.py ValueError

### ISSUE THREAD

**Issue by martbrob** [DRL/kinfin#27]
Hello,

I'm trying to run the functional_annotation_of_clusters.py script on the example data set provided with kinfin, but get the following error:

python functional_annotation_of_clusters.py all -f exampleannotations.functional_annotation.txt -c kinfin_example_results/cluster_counts_by_taxon.txt
[+] Start ...
[+] Parsing kinfin_example_results/cluster_counts_by_taxon.txt ...
[+] Parsing exampleannotations.functional_annotation.txt ...
Traceback (most recent call last):
  File "functional_annotation_of_clusters.py", line 249, in <module>
    dataCollection = DataCollection(args)
  File "functional_annotation_of_clusters.py", line 142, in __init__
    self.parse_cluster_metrics()
  File "functional_annotation_of_clusters.py", line 185, in parse_cluster_metrics
    protein_count = int(col[4])
ValueError: invalid literal for int() with base 10: 'PF00397:2'

What could the issue be? Thanks.

**Comment by tommathers** [comment]
I had this when I tried to run it with the functional annotation file used as input to kinfi. Try using one of the annotation files in the kinfin results folder. 

Example line that worked for me:

`python /nbi/software/testing/kinfin/1.0.3/x86_64/bin/functional_annotation_of_clusters.py all -f ./kinfin_results/cluster_domain_annotation.IPR.txt -c ./kinfin_results/cluster_counts_by_taxon.txt -p 0.75 -x 0.75 -o interpro`

**Comment by yuzhenpeng** [comment]
[WARN] - PFAM-ID file 'data/Pfam-A.clans.tsv.gz' not found.
