### ISSUE TITLE
Config File with TAXID or other labels

### ISSUE THREAD

**Issue by agcmartins** [DRL/kinfin#32]
Hi,
First congratulation, Kinfin is a good software. I'm using Kinfin but when I tried to do a advanced anlysis I'm facing the following error:

[STATUS]         - Clusters found = 722944   
[STATUS] - Analysing clusters ...
Traceback (most recent call last):
  File "/home/agcmartins/programs/kinfin/src/kinfin.py", line 2317, in <module>
    aloCollection.analyse_clusters()
  File "/home/agcmartins/programs/kinfin/src/kinfin.py", line 1420, in analyse_clusters
    self.analyse_cluster(clusterObj)
  File "/home/agcmartins/programs/kinfin/src/kinfin.py", line 1544, in analyse_cluster
    mwu_pvalue, mwu_log2_mean, mean_ALO_count, mean_non_ALO_count = statistic(ALO_proteome_counts_in_cluster, n
on_ALO_proteome_counts_in_cluster, inputObj.test)
  File "/home/agcmartins/programs/kinfin/src/kinfin.py", line 171, in statistic
    pvalue = scipy.stats.mannwhitneyu(implicit_count_1, implicit_count_2, alternative="two-sided")[1]
AttributeError: 'module' object has no attribute 'stats'

However, if I remove TAXID and any also any other label than " IDX,TAXON,OUT " the kinfin works without any problem. I've tried to run using example data with ./test and also the /supplementary_data_2/ using commands recommended in README file and got the same issue. I also tried to download and install it again, but it didn't solve the problem. 

Best regards,
André Guilherme

**Comment by clydeandforth** [comment]
Hi,
I got the same error. To get around it I added:

`import scipy.stats`

I put this on line 67, below `import gzip`

James

**Comment by agcmartins** [comment]
Hi James,
Thank you very much! The problem is solved!
Best regards,
André Guilherme

**Comment by DRL** [comment]
Should work now in v1.1, see readme.
