### ISSUE TITLE
I have a problen to run Kinfin

### ISSUE THREAD

**Issue by icruz1989** [DRL/kinfin#37]
Hello I want to run Kinfin but I get this message when I try to run ./test 

File "/home/icruz/apps/kinfin/src/kinfin.py", line 113
    print "[STATUS] - Downloading '%s' to '%s'." % (remote_f, local_f)

Any idea of what is happening?

**Comment by Jixin-Cao** [comment]
I meet a common question，have you solved it?

**Comment by icruz1989** [comment]
Hello, unfortunately not. The authors of the program did not respond.
________________________________
De: Jixin-Cao <notifications@github.com>
Enviado: martes, 17 de diciembre de 2019 02:17 p. m.
Para: DRL/kinfin <kinfin@noreply.github.com>
CC: IVAN DE LA CRUZ <soufly69@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [DRL/kinfin] I have a problen to run Kinfin (#37)


I meet a common question，have you solved it?

**Comment by glmaala** [comment]
hi, were you able to troubleshoot this?

**Comment by DRL** [comment]
Should work now in v1.1, see readme.
