### ISSUE TITLE
can't run kinfin

### ISSUE THREAD

**Issue by pnatsi** [DRL/kinfin#38]
I get this error message when first trying to run kinfin

lineage = {taxrank: 'undef' for taxrank in inputObj.taxranks}

**Comment by DRL** [comment]
Hi pnatsi,

Yeah, sorry... the software has eroded a bit. I am in the process of preparing a major release but it will take a while, since I am working mainly on other projects at the moment. 

Could you paste the actual command you ran and the full output to the terminal?

cheers, 

dom

**Comment by pnatsi** [comment]
$ ./kinfin
  File "/home/natsidis/tools/kinfin/src/kinfin.py", line 193
    lineage = {taxrank: 'undef' for taxrank in inputObj.taxranks}
                                  ^
SyntaxError: invalid syntax
