### ISSUE TITLE
Installation error: No module named 'pip.req'

### ISSUE THREAD

**Issue by ggavelis** [DRL/kinfin#40]
Hello,
Looking forward to using your program but I get this installation error right out of the gate:
When I run **./install** It returns:

  **File "setup.py", line 4, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'**

I'd appreciate any help you can provide.

**Comment by glmaala** [comment]
hi, were you able to troubleshoot this?

**Comment by DRL** [comment]
Should work now in v1.1, see readme.
