### ISSUE TITLE
Installation error: No module named 'pip.req'

### ISSUE THREAD

**Issue by starise-wg** [DRL/kinfin#42]
Checking dependencies...
    [+] [wget] /root/.conda/envs/zhylb/bin/wget
    [+] [gunzip] /usr/bin/gunzip
    [+] [pip] /root/.conda/envs/zhylb/bin/pip
    [+] [python] /root/.conda/envs/zhylb/bin/python
[+] Checking data files...
    [+] Extracting /root/kinfin/data/nodesdb.gz ...done.
    [-] /root/kinfin/data/Pfam-A.clans.tsv.gz. Downloading ftp://ftp.ebi.ac.uk/pub/databases/Pfamsv.gz ...done.
    [-] /root/kinfin/data/entry.list. Downloading ftp://ftp.ebi.ac.uk/pub/databases/interpro/entrone.
    [-] /root/kinfin/data/interpro2go. Downloading ftp://ftp.ebi.ac.uk/pub/databases/interpro/int. done.
[+] Installing python dependencies...
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
[+] Creating executable...
[+] Kinfin was installed. Please run ./kinfin
(zhylb) [root@hecs-x-xlarge-2-linux-20200326141032 kinfin]# ./kinfin
  File "/root/kinfin/src/kinfin.py", line 113
    print "[STATUS] - Downloading '%s' to '%s'." % (remote_f, local_f)
          ^
SyntaxError: invalid syntax

**Comment by glmaala** [comment]
hi, were you able to troubleshoot this?

**Comment by DRL** [comment]
Should work now in v1.1, see readme.
