### ISSUE TITLE
installation and running error

### ISSUE THREAD

**Issue by glmaala** [DRL/kinfin#44]
Here is the output when installing and running ./kinfin

(base) glmaala@DESKTOP-74AOEGG:~/kinfin$ `./install`

[+] Checking dependencies...
    [+] [wget] /home/glmaala/anaconda3/bin/wget
    [+] [gunzip] /usr/bin/gunzip
    [+] [pip] /home/glmaala/anaconda3/bin/pip
    [+] [python] /home/glmaala/anaconda3/bin/python
[+] Checking data files...
    [+] /home/glmaala/kinfin/data/nodesdb.txt
    [+] /home/glmaala/kinfin/data/Pfam-A.clans.tsv.gz
    [-] /home/glmaala/kinfin/data/entry.list. Downloading ftp://ftp.ebi.ac.uk/pub/databases/interpro/entry.list ...FAIL.    [-] /home/glmaala/kinfin/data/interpro2go. Downloading ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro2go ... FAIL.
[+] Installing python dependencies...
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
[+] Creating executable...
[+] Kinfin was installed. Please run ./kinfin

(base) glmaala@DESKTOP-74AOEGG:~/kinfin$ `./kinfin`

  File "/home/glmaala/kinfin/src/kinfin.py", line 113
    print "[STATUS] - Downloading '%s' to '%s'." % (remote_f, local_f)
          ^
SyntaxError: invalid syntax

kinfin.py or kinfin-d.py don't work when i'm trying to run the package. please help.

**Comment by DRL** [comment]
Should work now in v1.1, see readme.
