### ISSUE TITLE
Error in sanitise proteins step

### ISSUE THREAD

**Issue by aebaci** [DRL/kinfin#46]
./filter_fastas_before_clustering.py -f /home/WorkKinfin/ACYPI.Acyrthosyphon_pisum.faa -p 0 -l 30 -s 0
  File "./filter_fastas_before_clustering.py", line 33
    print ">%s.%s\n%s" % (self.prefix, self.header, self.seq)
                     ^
SyntaxError: invalid syntax

I get the same error when I try the example parallel code (but several times).

**Comment by DRL** [comment]
Hey, 

I made some changes, could you do `git pull` in the kinfin folder and try again?

cheers, 

dom

**Comment by DRL** [comment]
Cool. Glad I could help.

In the parallel command the `-f` was missing. Kinfin gets confused when there is no `-f`. This command should work.
```
parallel -j1 '~/kinfin/scripts/filter_fastas_before_clustering.py -f {} > {/.}.sl.faa' ::: /home/antonella/WorkKinfin/*faa
```
Will close this issue now and if more things come up you just keep opening new issues.

cheers, 

dom
