### ISSUE TITLE
Error in iprs2table.py

### ISSUE THREAD

**Issue by aebaci** [DRL/kinfin#48]
Hi:
When trying to run the iprs2table.py I get this error:

./iprs2table.py -i ~/WorkKinfin/Kinfin1Interproscan/allprotskinfin.faa.tsv --domain_sources Pfam Traceback (most recent call last):
  File "./iprs2table.py", line 19, in <module>
    import collections.Counter
ModuleNotFoundError: No module named 'collections.Counter'

**Comment by DRL** [comment]
Fixed in `main`. 

Do `git pull` in the kinfin folder and it should work now.

Reopen issue if not.

**Comment by DRL** [comment]
Try adjusting the program behaviour with the flags 
- `--domain_sources <STRING>`
- `--only_domain_go` 
- `--only_domain_ipr` 

(see [docs](https://kinfin.readme.io/docs/iprs2tablepy))

If the problem persists, please post the first 10 lines of `~/WorkKinfin/Kinfin1Interproscan/allprotskinfin.faa.tsv`

cheers, 

dom

**Comment by DRL** [comment]
Which version of interproscan did you use to make this file? And what was the command?

**Comment by DRL** [comment]
can you try again? i made a small change which should make it work now

**Comment by DRL** [comment]
They seem to have changed the format a bit ...

`iprs2table.py` checks for GO strings in the last column. You seem to have `-` in the last column (not sure why)... If you remove that column of `-` it might work.
